### ISSUE TITLE
Upgrade pro Laravel 5.1

### ISSUE THREAD

**Issue by ricardobarantini** [wesleywillians/laravel-pagseguro#3]
Tem algum plano para fazer o upgrade do package pro Laravel 5.1?

**Comment by wesleywillians** [comment]
Na realidade ele é compatível com a 5.1

**Comment by ricardobarantini** [comment]
Tentei instalar e deu erro, na pressa achei que fosse alguma incompatibilidade com o Laravel, mas acabei vendo o erro e é porque o composer não conseguiu instalar o package.

Resolvi meu problema de instalação incluindo as seguintes linhas no meu composer.json

``` javascript
"prefer-stable": true,
"minimum-stability": "dev"
```
